spring:
  datasource:
    url: jdbc:postgresql://ep-royal-bar-agsf4moz-pooler.c-2.eu-central-1.aws.neon.tech:5432/JoinMatch?sslmode=require&currentSchema=public
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
#    jpa:
#      hibernate:
#        ddl-auto: none
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#      show-sql: true